spring:
  application:
    name: RuralWell

  datasource:
    url: jdbc:postgresql://localhost:5432/serviciosocial
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  docker:
    compose:
      enabled: false

app:
  jwt:
    secret: "clave-super-secreta-de-al-menos-256-bits-para-jwt-hmac-sha"
    expiration: 86400000  # 24 horas en ms

  openai:
    api-key: "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"
    model: "gpt-4o-mini"
    max-tokens: 1000
    base-url: "https://api.openai.com/v1"

  cors:
    allowed-origins: "http://localhost:5173,http://localhost:5174"
